import type { CostMode } from '#/api/cost';

const ROAD_PREVIEW = [
  {
    baseFreight: 425,
    chassis: 45,
    city: 'DUNDEE',
    extraFields: { cf_demo: '示例值' },
    fsc: 0.35,
    id: 1,
    logYardNameAddress: '',
    zipCode: '44624',
    pol: 'NOR/NY',
    por: 'COLUMBUS',
    remark: '预览数据',
    state: 'OH',
    supplier: 'TIIME DISPATCH',
    validDate: '2026.06.01',
  },
  {
    baseFreight: 410,
    chassis: 45,
    city: 'COLUMBUS',
    extraFields: {},
    fsc: 0.35,
    id: 2,
    logYardNameAddress: '',
    zipCode: '43215',
    pol: 'NOR/NY',
    por: 'COLUMBUS',
    remark: '—',
    state: 'OH',
    supplier: 'TIIME DISPATCH',
    validDate: '2026.06.01',
  },
  {
    baseFreight: 398,
    chassis: 42,
    city: 'TOLEDO',
    extraFields: {},
    fsc: 0.33,
    id: 3,
    logYardNameAddress: '',
    zipCode: '43604',
    pol: 'LALB/NY',
    por: 'TOLEDO',
    remark: '—',
    state: 'OH',
    supplier: 'ABC LOGISTICS',
    validDate: '2026.06.15',
  },
  {
    baseFreight: 455,
    chassis: 48,
    city: 'DETROIT',
    extraFields: {},
    fsc: 0.36,
    id: 4,
    logYardNameAddress: '',
    zipCode: '48201',
    pol: 'DET/MI',
    por: 'DETROIT',
    remark: '旺季加价',
    state: 'MI',
    supplier: 'FAST HAUL',
    validDate: '2026.07.01',
  },
];

const FREIGHT_PREVIEW = [
  {
    allIn: 700,
    buc: 100,
    carrier: 'YML',
    currency: 'USD',
    destination: 'SHANGHAI/NINGBO/YANTIAN',
    extraFields: {},
    id: 1,
    origin: 'LOUISVILLE',
    remark: '预览数据',
    spec: '',
    status: 'active',
    surchargeValidDate: '2026-04-13',
    unit: '箱',
    unitPrice: 600,
    updatedAt: '2026-06-01 10:00',
    validDate: '2026/6/30',
    validFrom: '',
    validTo: '',
  },
  {
    allIn: 680,
    buc: 95,
    carrier: 'COSCO',
    currency: 'USD',
    destination: 'Los Angeles',
    extraFields: {},
    id: 2,
    origin: 'Chicago',
    remark: '—',
    spec: '',
    status: 'active',
    surchargeValidDate: '2026-05-01',
    unit: '箱',
    unitPrice: 585,
    updatedAt: '2026-06-02 11:20',
    validDate: '2026/7/15',
    validFrom: '',
    validTo: '',
  },
  {
    allIn: 1620,
    buc: 120,
    carrier: 'EMC',
    currency: 'USD',
    destination: 'Oakland',
    extraFields: {},
    id: 3,
    origin: 'Qingdao',
    remark: '—',
    spec: '',
    status: 'draft',
    surchargeValidDate: '2026-06-10',
    unit: '箱',
    unitPrice: 1500,
    updatedAt: '2026-06-03 09:15',
    validDate: '2026/8/10',
    validFrom: '',
    validTo: '',
  },
];

const FUMIGATION_PREVIEW = [
  {
    extraFields: {},
    id: 1,
    nonOakIndoor: 900,
    nonOakOutdoor: 800,
    nonOakQuoteSummer: '850',
    nonOakQuoteWinter: '850+100',
    oakIndoor: 1580,
    oakOutdoor: 1480,
    oakQuoteSummer: '1550',
    oakQuoteWinter: '1680+100',
    port: 'CHICAGO',
    remark: '预览数据',
    station: 'EFM',
    updatedAt: '2026-06-01 10:00',
  },
  {
    extraFields: {},
    id: 2,
    nonOakIndoor: 920,
    nonOakOutdoor: 810,
    nonOakQuoteSummer: '860',
    nonOakQuoteWinter: '860+100',
    oakIndoor: 1600,
    oakOutdoor: 1500,
    oakQuoteSummer: '1580',
    oakQuoteWinter: '1700+100',
    port: 'LOS ANGELES',
    remark: '—',
    station: 'APM',
    updatedAt: '2026-06-02 11:20',
  },
];

export function getTemplatePreviewRows(mode: CostMode) {
  if (mode === 'road') {
    return ROAD_PREVIEW;
  }
  if (mode === 'sea') {
    return FREIGHT_PREVIEW;
  }
  if (mode === 'fumigation') {
    return FUMIGATION_PREVIEW;
  }
  return FREIGHT_PREVIEW;
}
