import type { CostMode } from '#/api/cost';

const ROAD_PREVIEW = [
  {
    allInFmOneWay: 1378.75,
    allInFmRound: 1488.75,
    allInNoFm: 1288.75,
    baseFreight: 425,
    chassis: 45,
    city: 'DALTON',
    extraFields: {
      cf_demo: '示例值',
      cf_road_extra_chassis: 45,
      cf_road_extra_chassis_unit: 'day',
      cf_road_waiting_unit: 'hours',
      cf_road_yard_storage: 80,
      cf_road_yard_storage_unit: 'day',
    },
    fsc: 35,
    id: 1,
    logYardNameAddress: '712 SR 1830 Brookeville, PA 15825',
    otherFee: 75,
    pol: 'NOR/NY',
    por: 'DALTON',
    prepull: 120,
    redelivery: 150,
    remark: '预览数据',
    split: 50,
    state: 'OH',
    stopOff: 85,
    supplier: 'TIIME DISPATCH',
    nsLift: 150,
    triTandemAxle: 200,
    validDate: '2026-06-01',
    waitingFee: 90,
    zipCode: '44624',
  },
  {
    allInFmOneWay: 688.5,
    allInFmRound: 798.5,
    allInNoFm: 598.5,
    baseFreight: 410,
    chassis: 45,
    city: 'COLUMBUS',
    extraFields: {},
    fsc: 35,
    id: 2,
    logYardNameAddress: '',
    otherFee: 70,
    pol: 'NOR/NY',
    por: 'COLUMBUS',
    prepull: 0,
    redelivery: 140,
    remark: '—',
    split: 0,
    state: 'OH',
    stopOff: 0,
    supplier: 'TIIME DISPATCH',
    nsLift: 140,
    triTandemAxle: 0,
    validDate: '2026-06-01',
    waitingFee: 85,
    zipCode: '43215',
  },
  {
    allInFmOneWay: 1274.25,
    allInFmRound: 1354.25,
    allInNoFm: 1194.25,
    baseFreight: 455,
    chassis: 50,
    city: 'CLEVELAND',
    extraFields: {},
    fsc: 35,
    id: 3,
    logYardNameAddress: '',
    otherFee: 80,
    pol: 'NOR/NY',
    por: 'CLEVELAND',
    prepull: 110,
    redelivery: 155,
    remark: '—',
    split: 40,
    state: 'OH',
    stopOff: 75,
    supplier: 'MIDWEST DRAYAGE LLC',
    nsLift: 155,
    triTandemAxle: 180,
    validDate: '2026-06-01',
    waitingFee: 95,
    zipCode: '44114',
  },
];

const FREIGHT_PREVIEW = [
  {
    allIn: 700,
    buc: 100,
    carrier: 'YML',
    currency: 'USD',
    destination: 'SHANGHAI/NINGBO/YANTIAN',
    extraFields: {},
    id: 1,
    origin: 'LOUISVILLE',
    remark: '预览数据',
    spec: '',
    status: 'active',
    surchargeValidDate: '2026-04-13',
    unit: '箱',
    unitPrice: 600,
    updatedAt: '2026-06-01 10:00',
    validDate: '2026/6/30',
    validFrom: '',
    validTo: '',
  },
  {
    allIn: 680,
    buc: 95,
    carrier: 'COSCO',
    currency: 'USD',
    destination: 'Los Angeles',
    extraFields: {},
    id: 2,
    origin: 'Chicago',
    remark: '—',
    spec: '',
    status: 'active',
    surchargeValidDate: '2026-05-01',
    unit: '箱',
    unitPrice: 585,
    updatedAt: '2026-06-02 11:20',
    validDate: '2026/7/15',
    validFrom: '',
    validTo: '',
  },
  {
    allIn: 1620,
    buc: 120,
    carrier: 'EMC',
    currency: 'USD',
    destination: 'Oakland',
    extraFields: {},
    id: 3,
    origin: 'Qingdao',
    remark: '—',
    spec: '',
    status: 'active',
    surchargeValidDate: '2026-06-10',
    unit: '箱',
    unitPrice: 1500,
    updatedAt: '2026-06-03 09:15',
    validDate: '2026/8/10',
    validFrom: '',
    validTo: '',
  },
];

const FUMIGATION_PREVIEW = [
  {
    extraFields: {},
    id: 1,
    nonOakIndoor: 900,
    nonOakOutdoor: 800,
    nonOakQuoteSummer: '850',
    nonOakQuoteWinter: '850+100',
    oakIndoor: 1580,
    oakOutdoor: 1480,
    oakQuoteSummer: '1550',
    oakQuoteWinter: '1680+100',
    port: 'CHICAGO',
    remark: '预览数据',
    station: 'EFM',
    updatedAt: '2026-06-01 10:00',
  },
  {
    extraFields: {},
    id: 2,
    nonOakIndoor: 920,
    nonOakOutdoor: 810,
    nonOakQuoteSummer: '860',
    nonOakQuoteWinter: '860+100',
    oakIndoor: 1600,
    oakOutdoor: 1500,
    oakQuoteSummer: '1580',
    oakQuoteWinter: '1700+100',
    port: 'LOS ANGELES',
    remark: '—',
    station: 'APM',
    updatedAt: '2026-06-02 11:20',
  },
];

export function getTemplatePreviewRows(mode: CostMode) {
  if (mode === 'road') {
    return ROAD_PREVIEW;
  }
  if (mode === 'sea') {
    return FREIGHT_PREVIEW;
  }
  if (mode === 'fumigation') {
    return FUMIGATION_PREVIEW;
  }
  return FREIGHT_PREVIEW;
}
