import type { FieldCatalogEntry } from './types';

const road = (key: string) => `page.costLibrary.roadFields.${key}`;

export const ROAD_FIELD_CATALOG: FieldCatalogEntry[] = [
  {
    field: 'validDate',
    group: 'basic',
    labelKey: road('validDate'),
    minWidth: 112,
  },
  {
    field: 'supplier',
    group: 'basic',
    labelKey: road('supplier'),
    minWidth: 150,
  },
  {
    field: 'logYardNameAddress',
    group: 'basic',
    labelKey: road('logYardNameAddress'),
    minWidth: 200,
    showOverflow: true,
  },
  {
    field: 'city',
    group: 'basic',
    labelKey: road('city'),
    minWidth: 100,
  },
  {
    field: 'state',
    group: 'basic',
    labelKey: road('state'),
    minWidth: 72,
  },
  {
    field: 'por',
    group: 'basic',
    labelKey: road('por'),
    minWidth: 100,
  },
  {
    field: 'pol',
    group: 'basic',
    labelKey: road('pol'),
    minWidth: 92,
  },
  {
    align: 'right',
    className: 'col-price',
    field: 'baseFreight',
    format: 'amount',
    group: 'freight',
    labelKey: road('baseFreight'),
    minWidth: 108,
  },
  {
    align: 'right',
    className: 'col-price',
    field: 'fsc',
    format: 'percent',
    group: 'freight',
    labelKey: road('fsc'),
    minWidth: 72,
  },
  {
    align: 'right',
    className: 'col-price',
    field: 'chassis',
    format: 'amount',
    group: 'freight',
    labelKey: road('chassis'),
    minWidth: 88,
  },
  {
    align: 'right',
    className: 'col-price',
    field: 'owTriAxle',
    format: 'amount',
    group: 'freight',
    labelKey: road('owTriAxle'),
    minWidth: 112,
  },
  {
    align: 'right',
    className: 'col-price',
    field: 'split',
    format: 'amount',
    group: 'freight',
    labelKey: road('split'),
    minWidth: 80,
  },
  {
    align: 'right',
    className: 'col-price',
    field: 'stopOff',
    format: 'amount',
    group: 'freight',
    labelKey: road('stopOff'),
    minWidth: 92,
  },
  {
    align: 'right',
    className: 'col-price',
    field: 'allIn',
    format: 'amount',
    group: 'freight',
    labelKey: road('allIn'),
    minWidth: 108,
  },
  {
    align: 'right',
    className: 'col-price',
    field: 'allInNonOak',
    format: 'amount',
    group: 'freight',
    labelKey: road('allInNonOak'),
    minWidth: 128,
  },
  {
    align: 'right',
    className: 'col-price',
    field: 'allInOak',
    format: 'amount',
    group: 'freight',
    labelKey: road('allInOak'),
    minWidth: 112,
  },
  {
    align: 'right',
    className: 'col-price',
    field: 'waitingFee',
    format: 'amount',
    group: 'surcharge',
    labelKey: road('waitingFee'),
    minWidth: 100,
  },
  {
    align: 'right',
    className: 'col-price',
    field: 'redelivery',
    format: 'amount',
    group: 'surcharge',
    labelKey: road('redelivery'),
    minWidth: 100,
  },
  {
    align: 'right',
    className: 'col-price',
    field: 'prepull',
    format: 'amount',
    group: 'surcharge',
    labelKey: road('prepull'),
    minWidth: 88,
  },
  {
    align: 'right',
    className: 'col-price',
    field: 'nsLift',
    format: 'amount',
    group: 'surcharge',
    labelKey: road('nsLift'),
    minWidth: 88,
  },
  {
    className: 'col-remark',
    field: 'remark',
    group: 'surcharge',
    labelKey: road('remark'),
    minWidth: 160,
    showOverflow: true,
  },
];
