import type { FieldCatalogEntry } from './types';

const f = (key: string) => `page.costLibrary.seaFields.${key}`;

/** 海运成本库标准列：对齐业务 Excel 表头 */
export const SEA_FIELD_CATALOG: FieldCatalogEntry[] = [
  { field: 'por', labelKey: f('por'), minWidth: 110, width: 120 },
  { field: 'pol', labelKey: f('pol'), minWidth: 110, width: 120 },
  { field: 'pod', labelKey: f('pod'), minWidth: 120, width: 140 },
  {
    field: 'cnShortName',
    labelKey: f('cnShortName'),
    minWidth: 100,
    width: 110,
  },
  {
    field: 'enProductName',
    labelKey: f('enProductName'),
    minWidth: 160,
    showOverflow: true,
    width: 180,
  },
  {
    field: 'containerType',
    labelKey: f('containerType'),
    minWidth: 140,
    width: 160,
  },
  {
    align: 'right',
    className: 'col-price',
    field: 'freight',
    format: 'amount',
    labelKey: f('freight'),
    minWidth: 100,
    width: 110,
  },
  {
    field: 'freightValidDate',
    labelKey: f('freightValidDate'),
    minWidth: 110,
    width: 120,
  },
  {
    align: 'right',
    field: 'buc',
    format: 'amount',
    labelKey: f('buc'),
    minWidth: 80,
    width: 90,
  },
  {
    field: 'bucValidDate',
    labelKey: f('bucValidDate'),
    minWidth: 100,
    width: 110,
  },
  {
    align: 'right',
    field: 'ebs',
    format: 'amount',
    labelKey: f('ebs'),
    minWidth: 80,
    width: 90,
  },
  {
    field: 'ebsValidDate',
    labelKey: f('ebsValidDate'),
    minWidth: 100,
    width: 110,
  },
  {
    align: 'right',
    field: 'gri',
    format: 'amount',
    labelKey: f('gri'),
    minWidth: 80,
    width: 90,
  },
  {
    field: 'griValidDate',
    labelKey: f('griValidDate'),
    minWidth: 100,
    width: 110,
  },
  {
    align: 'right',
    field: 'others',
    format: 'amount',
    labelKey: f('others'),
    minWidth: 90,
    width: 100,
  },
  {
    field: 'othersValidDate',
    labelKey: f('othersValidDate'),
    minWidth: 110,
    width: 120,
  },
  {
    align: 'right',
    className: 'col-price',
    field: 'allIn',
    format: 'amount',
    labelKey: f('allIn'),
    minWidth: 110,
    width: 120,
  },
  { field: 'ssl', labelKey: f('ssl'), minWidth: 100, width: 110 },
  { field: 'agent', labelKey: f('agent'), minWidth: 100, width: 110 },
  {
    className: 'col-remark',
    field: 'remark',
    labelKey: f('remark'),
    minWidth: 140,
    showOverflow: true,
  },
];
