import type { FieldCatalogEntry } from './types';

const f = (key: string) => `page.costLibrary.seaFields.${key}`;

/** 海运字段目录：列宽贴合表头；默认展示顺序见 default-templates */
export const SEA_FIELD_CATALOG: FieldCatalogEntry[] = [
  { field: 'por', labelKey: f('por'), minWidth: 72, width: 72 },
  { field: 'pol', labelKey: f('pol'), minWidth: 72, width: 72 },
  { field: 'pod', labelKey: f('pod'), minWidth: 80, width: 80 },
  {
    align: 'right',
    className: 'col-price',
    field: 'freight',
    format: 'amount',
    labelKey: f('freight'),
    minWidth: 80,
    width: 80,
  },
  {
    field: 'containerType',
    labelKey: f('containerType'),
    minWidth: 80,
    width: 80,
  },
  {
    field: 'freightValidDate',
    format: 'dateMmDd',
    labelKey: f('freightValidDate'),
    minWidth: 52,
    width: 52,
  },
  {
    align: 'right',
    field: 'buc',
    format: 'amount',
    labelKey: f('buc'),
    minWidth: 100,
    width: 100,
  },
  {
    field: 'bucValidDate',
    format: 'dateMmDd',
    labelKey: f('bucValidDate'),
    minWidth: 52,
    width: 52,
  },
  {
    align: 'right',
    field: 'others',
    format: 'amount',
    labelKey: f('others'),
    minWidth: 80,
    width: 80,
  },
  {
    field: 'othersValidDate',
    format: 'dateMmDd',
    labelKey: f('othersValidDate'),
    minWidth: 52,
    width: 52,
  },
  {
    align: 'right',
    className: 'col-price',
    field: 'allIn',
    format: 'amount',
    labelKey: f('allIn'),
    minWidth: 120,
    width: 120,
  },
  {
    field: 'ssl',
    labelKey: f('ssl'),
    minWidth: 110,
    showOverflow: true,
    width: 110,
  },
  {
    field: 'agent',
    labelKey: f('agent'),
    minWidth: 110,
    showOverflow: true,
    width: 110,
  },
  {
    className: 'col-remark',
    field: 'remark',
    labelKey: f('remark'),
    minWidth: 120,
    showOverflow: true,
    width: 120,
  },
  {
    field: 'enProductName',
    labelKey: f('enProductName'),
    minWidth: 100,
    showOverflow: true,
    width: 100,
  },
  // 以下为字段库可选项（默认模板不展示）
  {
    field: 'cnShortName',
    labelKey: f('cnShortName'),
    minWidth: 96,
    showOverflow: true,
    width: 96,
  },
  {
    align: 'right',
    field: 'ebs',
    format: 'amount',
    labelKey: f('ebs'),
    minWidth: 64,
    width: 64,
  },
  {
    field: 'ebsValidDate',
    format: 'dateMmDd',
    labelKey: f('ebsValidDate'),
    minWidth: 52,
    width: 52,
  },
  {
    align: 'right',
    field: 'gri',
    format: 'amount',
    labelKey: f('gri'),
    minWidth: 64,
    width: 64,
  },
  {
    field: 'griValidDate',
    format: 'dateMmDd',
    labelKey: f('griValidDate'),
    minWidth: 52,
    width: 52,
  },
];
